### ISSUE TITLE
Setting the GOPATH doesn't seem to override the environment

### ISSUE THREAD

**Issue by manavo** [joefitzgerald/go-config#60]
I tried setting a specific GOPATH in the config (even if discouraged) but I couldn't get it to override the environment GOPATH.

If it makes a difference, it was a few paths joined by ":"s (/path1/gopath:/path2/gopath:/path3/gopath)

**Comment by joefitzgerald** [comment]
The config option for GOPATH is akin to a fallback. If your GOPATH is somehow undefined (e.g. you launch Atom from the Ubuntu launcher, instead of the terminal), then you will still be able to use go-plus.

On OS X, provided you are a user of sh, bash, zsh, or fish, your environment should always be sane and be the product of running your shell initialization script(s).

**Comment by manavo** [comment]
Ah, OK! I thought it would be more of an override (as it used to be), not just a fallback. My misunderstanding then! Thanks for clarifying :)
